<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows10.0.19041.0;net9.0-windows10.0.19041.0;net10.0-windows10.0.19041.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <WindowsSdkPackageVersion>10.0.26100.80</WindowsSdkPackageVersion>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Wslc.Testcontainers\Wslc.Testcontainers.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.Valkey\Wslc.Testcontainers.Modules.Valkey.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.MariaDb\Wslc.Testcontainers.Modules.MariaDb.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.RabbitMq\Wslc.Testcontainers.Modules.RabbitMq.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.MongoDb\Wslc.Testcontainers.Modules.MongoDb.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.Nats\Wslc.Testcontainers.Modules.Nats.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.MailPit\Wslc.Testcontainers.Modules.MailPit.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.RustFs\Wslc.Testcontainers.Modules.RustFs.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.WireMock\Wslc.Testcontainers.Modules.WireMock.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.Qdrant\Wslc.Testcontainers.Modules.Qdrant.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.ClickHouse\Wslc.Testcontainers.Modules.ClickHouse.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.Vault\Wslc.Testcontainers.Modules.Vault.csproj" />
    <ProjectReference Include="..\..\src\Wslc.Testcontainers.Modules.Keycloak\Wslc.Testcontainers.Modules.Keycloak.csproj" />
  </ItemGroup>

</Project>
